name: app_lv
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^4.0.4
  video_player: ^2.9.1
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  persistent_header_adaptive: ^2.1.0
  image_picker: ^1.1.2
  http: ^1.2.2
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  input_quantity: ^2.4.1
  animated_text_kit: ^4.2.2
  socket_io_client: ^3.0.2
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/kid/
    - assets/icons/order/
    - assets/icons/payment/
    - assets/logo/
    - assets/image/homepage/
    - assets/image/shop/
    - assets/image/favorite/
    - assets/image/cart/
    - assets/image/shop/men/
    - assets/image/shop/women/
    - assets/image/shop/kid/
    - assets/image/account/system/
    - assets/video/
